import { Task, Member } from './types';

export const ADMIN_PAYMENT_NUMBER = '3024468046';

export const INITIAL_TASKS: Task[] = [
  // DEBERES (No requieren foto)
  {
    id: 'd1',
    title: 'Aseo de cuarto',
    description: 'Organizar y limpiar el espacio personal',
    xp: 20,
    fine: 2000,
    value: 2000,
    status: 'pending',
    icon: 'Bed',
    category: 'Limpieza',
    taskType: 'duty',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'd2',
    title: 'Lavar plato donde comió',
    description: 'Limpiar inmediatamente después de usar',
    xp: 15,
    fine: 1000,
    value: 1500,
    status: 'pending',
    icon: 'Utensils',
    category: 'Cocina',
    taskType: 'duty',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'd3',
    title: 'Recoger ropa seca',
    description: 'Doblar y guardar la ropa del tendedero',
    xp: 15,
    fine: 1500,
    value: 2000,
    status: 'pending',
    icon: 'Shirt',
    category: 'Hogar',
    taskType: 'duty',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'd4',
    title: 'Lavar platos de preparación',
    description: 'Lavar lo usado para preparar desayuno, almuerzo o cena',
    xp: 25,
    fine: 3000,
    value: 4000,
    status: 'pending',
    icon: 'Coffee',
    category: 'Cocina',
    taskType: 'duty',
    dueDate: '2026-03-02T22:00:00'
  },
  // OBLIGACIONES (Requieren foto)
  {
    id: 'o1',
    title: 'Lavar platos cena/almuerzo',
    description: 'Lavar toda la loza después de la comida familiar',
    xp: 50,
    fine: 10000,
    value: 8000,
    status: 'pending',
    icon: 'Utensils',
    category: 'Cocina',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'o2',
    title: 'Hacer comida (Desayuno/Almuerzo/Cena)',
    description: 'Preparar la alimentación para la familia',
    xp: 60,
    fine: 12000,
    value: 10000,
    status: 'pending',
    icon: 'ChefHat',
    category: 'Cocina',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'o3',
    title: 'Aseo General',
    description: 'Limpieza profunda de áreas comunes',
    xp: 100,
    fine: 20000,
    value: 15000,
    status: 'pending',
    icon: 'Brush',
    category: 'Limpieza',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'o4',
    title: 'Sacar Basura',
    description: 'Llevar los residuos al punto de recolección',
    xp: 30,
    fine: 5000,
    value: 4000,
    status: 'pending',
    icon: 'Trash2',
    category: 'Hogar',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'o5',
    title: 'Lavar Baño',
    description: 'Limpieza y desinfección total del baño',
    xp: 80,
    fine: 15000,
    value: 12000,
    status: 'pending',
    icon: 'Droplets',
    category: 'Limpieza',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'o6',
    title: 'Aseo necesidades del perro',
    description: 'Limpiar y desinfectar área de mascotas',
    xp: 40,
    fine: 8000,
    value: 6000,
    status: 'pending',
    icon: 'Dog',
    category: 'Mascotas',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'o7',
    title: 'Bañar perro/gato',
    description: 'Higiene completa de la mascota',
    xp: 70,
    fine: 10000,
    value: 9000,
    status: 'pending',
    icon: 'Bath',
    category: 'Mascotas',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'o8',
    title: 'Lavar escaleras patio',
    description: 'Limpieza con agua y jabón de escaleras',
    xp: 50,
    fine: 8000,
    value: 7000,
    status: 'pending',
    icon: 'Droplets',
    category: 'Limpieza',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  },
  {
    id: 'o9',
    title: 'Organizar reciclaje',
    description: 'Separar residuos correctamente',
    xp: 30,
    fine: 4000,
    value: 3000,
    status: 'pending',
    icon: 'Trash2',
    category: 'Hogar',
    taskType: 'obligation',
    dueDate: '2026-03-02T22:00:00'
  }
];

export const MEMBERS: Member[] = [
  {
    id: 'kevin',
    name: 'Kevin',
    email: 'kevin@familia.com',
    password: '1234567890',
    role: 'admin',
    level: 1,
    xp: 0,
    hearts: 5,
    streak: 0,
    debt: -20000,
    monthlyDebt: 0,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
    progress: 0,
    paymentInfo: { type: 'nequi', number: ADMIN_PAYMENT_NUMBER },
    settings: { darkMode: false }
  },
  {
    id: 'jefa',
    name: 'Jefa',
    email: 'jefa@familia.com',
    password: '1234567890',
    role: 'admin',
    level: 1,
    xp: 0,
    hearts: 5,
    streak: 0,
    debt: -20000,
    monthlyDebt: 0,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jefa',
    progress: 0,
    paymentInfo: { type: 'nequi', number: ADMIN_PAYMENT_NUMBER },
    settings: { darkMode: false }
  },
  {
    id: 'styven',
    name: 'Styven',
    email: 'styven@familia.com',
    password: '123456',
    role: 'member',
    level: 1,
    xp: 0,
    hearts: 5,
    streak: 0,
    debt: -50000,
    monthlyDebt: 0,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Styven',
    progress: 0,
    paymentInfo: { type: 'nequi', number: '3000000001' },
    settings: { darkMode: false }
  },
  {
    id: 'isabella',
    name: 'Isabella',
    email: 'isabella@familia.com',
    password: '123456',
    role: 'member',
    level: 1,
    xp: 0,
    hearts: 5,
    streak: 0,
    debt: -50000,
    monthlyDebt: 0,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    progress: 0,
    paymentInfo: { type: 'nequi', number: '3000000002' },
    settings: { darkMode: false }
  }
];
